### PR TITLE
Updating exception syntax for Python 3

### LINKED ISSUE #1: Exception in Python 3
I got an exception when trying to use this nose plugin in a Python 3.3 environment.

```
(data-generation-arch-venv) dev-lpt:data-generation-mongo nestep$ nosetests --mongoengine
/Users/dev/dev/data-generation-arch-venv/lib/python3.3/site-packages/nose/plugins/manager.py:395: RuntimeWarning: Unable to load plugin mongoengine = nose_mongoengine:MongoEnginePlugin: invalid syntax (__init__.py, line 156)
  RuntimeWarning)
Usage: nosetests [options]

nosetests: error: no such option: --mongoengine
```

### PR DESCRIPTION
**Pull request by nikestep**
Fix #1

According to http://docs.python.org/3/howto/pyporting.html#capturing-the-currently-raised-exception this fix will be compatible with Python 2.6 and up, including Python 3.

### CODE REVIEW

**Comment by dayvson** [comment]
Thanks for that!

**Comment by nikestep** [comment]
Can you do a release with the change? I'm looking to use the plugin in a build chain.

**Comment by dayvson** [comment]
Hi @mbanton can you publish the build I already bump up the version.

**Comment by mbanton** [comment]
Hello @nikestep and @dayvson 

Thanks for the corrections. Just up the package to the PyPI repository. Sorry for the delay, I was on vacation in the last days.

Link to the package of the corrected version: https://pypi.python.org/pypi/nose-mongoengine/0.2.2

**Comment by nikestep** [comment]
Fixed the issue. Thanks much!

**Pull request merged**
